config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations]

  devise_scope :user do
    get 'users/sign_out', to: 'users/sessions#destroy'
    authenticated :user do
      root 'students#index', as: :authenticated_root
    end
    unauthenticated do
      root to: "users/sessions#new", as: nil
    end
  end

  resources :students do
    collection do
      get 'get_all_student_list'
      delete 'delete_student'
      post 'save_mass_data_upload'
      get 'get_student_data'
    end
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, length: { in: 3..30 }
  validates :subject, presence: true, length: { in: 3..20 }
  validates :marks, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  require 'csv'
  before_action :authenticate_user!
  def index
    @students = current_user.students
  end


  def create
    if current_user
      @student = current_user.students.find_or_initialize_by(name: student_params[:name], subject: student_params[:subject])
      @student.marks = student_params[:marks].to_i
  
      if @student.save
        render json: { success: true, message: "Student successfully created or updated!" }, status: :ok
      else
        render json: { success: false, errors: @student.errors.full_messages }, status: :unprocessable_entity
      end
    else
      render json: { success: false, message: "Not authenticated" }, status: :unauthorized
    end 
  end   

  def update
    if current_user
      @student = current_user.students.find(params[:id])
      if @student.update(student_params)
        render json: { success: true, message: "Student successfully updated!" }, status: :ok
      else
        render json: { success: false, errors: @student.errors.full_messages }, status: :unprocessable_entity
      end
    else
      redirect_to root_path
    end
  end  

  def delete_student
    if current_user
      ids = params[:ids]
      @students = current_user.students.where(id: ids)
  
      if @students.exists?
        @students.destroy_all
        render json: { message: 'Success' }
      else
        render json: { message: 'Students not found' }, status: :not_found
      end
    else
      redirect_to root_path
    end
  end  

  def get_all_student_list
    if current_user
      students = Student.where(user_id: current_user.id)
      if params[:search].present?
        filter = "%#{params[:search].upcase}%"
        students = students.where("students.name LIKE :filter OR students.subject LIKE :filter OR CAST(students.marks AS TEXT) LIKE :filter", filter: filter)
      end
      students_data = students.map do |student|
        { id: student.id, name: student.name, subject: student.subject, marks: student.marks }
      end
      render json: students_data
    else
      redirect_to root_path
    end
  end   

  def get_student_data
    data = Student.find(params[:id])
    render :json => data
  end

  def save_mass_data_upload
    if current_user
      csv_file = params[:csv_file]
      file_extension = File.extname(csv_file.original_filename)
      @error_msg = ""
  
      if file_extension == ".csv"
        total_count = 0
        directory = File.join(Rails.root, 'public', 'uploads')
        FileUtils.mkdir_p(directory, mode: 0777) unless File.directory?(directory)
        time = Time.now.strftime("%m_%d_%Y_%I_%M_%S%p")
        file_name = csv_file.original_filename.gsub(file_extension, "").gsub(" ", "_")
        target_file_name = "#{file_name}_#{time}#{file_extension}"
        target_file_name_path = File.join(directory, target_file_name)
  
        File.open(target_file_name_path, "wb") do |f|
          f.write(csv_file.read)
        end
  
        CSV.foreach(target_file_name_path, headers: true) do |row|
          Rails.logger.info("Processing row: #{row.inspect}")
          begin
            student_record = Student.find_or_initialize_by(name: row['Name'].upcase, subject: row['Subject'].upcase, user_id: current_user.id)
            student_record.marks = row['Marks'].to_i
            if student_record.changed?
              if student_record.save
                total_count += 1
              else
                Rails.logger.error("Failed to save student record: #{student_record.errors.full_messages.join(', ')}")
              end
            end
          rescue StandardError => e
            Rails.logger.error("Error processing CSV row: #{e.message}")
          end
        end
  
        @error_msg = total_count > 0 ? "File Processed Successfully: #{total_count} records updated." : "No new records were added."
      else
        @error_msg = "Format of file is not supported"
      end
      render plain: @error_msg
    else
      redirect_to root_path
    end
  end  

  private

  def student_params
    params.require(:student).permit(:name, :subject, :marks)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_student_edit.html.erb
<div class="modal-dialog modal-dialog-centered">
  <div class="modal-content">
    <div class="modal-header" style="margin: 0px 0px 10px 20px; display: flex;">
      <h4 class="modal-title">Edit Student</h4>
      <span style="margin-left: auto; cursor: pointer;" onclick="modalClose('editModal')">
        <i class="fa-solid fa-xmark fa-2xl"></i>
      </span>
    </div>
    <div class="modal-body">
      <div class="container" style="max-width: 550px;">
        <%= form_with url: '', html: { class: 'form-horizontal', id: 'editForm', onsubmit: 'event.preventDefault(); handleFormSubmit(this, "PATCH", "editModal");' } do |f| %>
          <%= render 'student_main', f: f %>
          <div class="actions">
            <%= f.button "Cancel", class: "btn btn-danger", type: "button", onclick: "modalClose('editModal')", style: "padding: 10px 20px;" %>
            <%= f.submit "Update", class: "btn btn-success", style: "padding: 10px 30px;" %>
          </div>
        <% end %>  
      </div>
    </div>
  </div>
</div>

app/views/students/_student_main.html.erb
<div class="student-form">
  <div class="form-group">
    <%= f.label :name, class: 'form-label' do %>
      Name <span class="text-danger">*</span>
    <% end %>
    <%= f.text_field :name, class: 'form-control', required: true, pattern: "[A-Z\\s]{3,30}", title: "Enter between 3 to 30 characters", maxlength: 30, oninput: "this.value = this.value.toUpperCase();" %>
  </div>
  <div class="form-group">
    <%= f.label :subject, class: 'form-label' do %>
      Subject <span class="text-danger">*</span>
    <% end %>
    <%= f.text_field :subject, class: 'form-control', required: true, pattern: "[A-Z\\s]{3,30}", title: "Enter between 3 to 20 characters", maxlength: 20, oninput: "this.value = this.value.toUpperCase();" %>
  </div>
  <div class="form-group">
    <%= f.label :marks, class: 'form-label' do %>
      Marks <span class="text-danger">*</span>
    <% end %>
    <%= f.number_field :marks, class: 'form-control', min: 0, max: 100, required: true %>
  </div>
</div>

app/views/students/_student_new.html.erb
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header" style="margin: 0px 0px 10px 20px; display: flex;">
            <h4 class="modal-title">Add Student</h4>
            <span style="margin-left: auto; cursor: pointer;" onclick="modalClose('addModal')">
                <i class="fa-solid fa-xmark fa-2xl"></i>
            </span>
        </div>
        <div class="modal-body">
            <div class="container" style="max-width: 550px; ">
                <%= form_with model: Student.new, url: students_path, method: :post, html: { class: 'form-horizontal', id: 'addForm', onsubmit: 'event.preventDefault(); handleFormSubmit(this, "POST", "addModal");' } do |f| %>
                    <%= render 'student_main', f: f %>
                <div class="actions">
                    <%= f.button "Cancel", class: "btn btn-danger", type: "button", onclick: "modalClose('addModal')", style: "padding: 10px 20px;" %>
                    <%= f.submit "Add", class: "btn btn-success", style: "padding: 10px 30px;" %>
                </div>
                <% end %>  
            </div>
        </div>
    </div>
</div>

app/views/students/_upload_student_csv_list.html.erb
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header" style="margin: 0px 0px 10px 20px;">
            <div style="display: flex">
                <h5 class="modal-title">Upload Student details</h5>
                <span style="margin-left: auto; cursor: pointer;" onclick="modalClose('uploadModal')">
                    <i class="fa-solid fa-xmark fa-2xl"></i>
                </span>
            </div>
            <span style="font-size: 13px; color: red;">(Format of File : students.csv)</span>
        </div>
        <div class="modal-body">
            <div style="margin: 0px 0px 10px 20px;"> 
                <label for="upload_file">Select File<span class="text-danger">*</span> :</label><br />
                <input type="file" id="upload_datafile" multiple name="upload[datafile]" accept=".csv">
            </div>
            <div style="margin-top: 44px;"> 
                <button id="uploadButton" class="btn btn-success" style="margin-right: 10px;">Upload</button>
                <button type="button" class="btn btn-danger" style="margin-left: 10px;" onclick="modalClose('uploadModal')">Close</button>
            </div>
            
            <div style="margin: 0px 0px 10px 20px;">
                <a href="sample_students.csv" download class="edit-profile-link">Download Sample CSV File</a>
            </div>
        </div>
    </div>
</div>

app/views/students/index.html.erb
<body style="background-color: #fff;">
    <span style="float: right; margin-right: 10px;">
        Welcome: <%= current_user.email %> | <%= link_to destroy_user_session_path, method: :delete do %>
        Logout
      <% end %>
    </span>
    <div style="margin: 10px 5px; display: flex;">
        <div style="display: flex; margin-right: 15px;">
            <button class="btn btn-primary" onclick="onBtnExport()"><i class="fa-solid fa-download fa-xs"></i> Export</button>
            <button class="btn btn-default" onclick="onBtnUpload()"><i class="fa-solid fa-upload fa-xs"></i> Upload</button>
            <button class="btn btn-success" onclick="onBtnAdd()"><i class="fa-solid fa-user-plus fa-xs"></i> Add</button>
            <button class="btn btn-primary" onclick="onBtnEdit()"><i class="fa-solid fa-user-edit fa-xs"></i> Edit</button>
            <button class="btn btn-danger" onclick="batchDelete()"><i class="fa-solid fa-user-minus fa-xs"></i> Delete</button>
            <div class="input-group rounded" style="margin-top: 20px; display: flex;">
                <input type="search" class="form-control rounded" placeholder="Search in .." onkeyup="handleSearchChange(this.value)" />
                <span class="input-group-text border-0"><i class="fas fa-search searchbar"></i></span>
            </div>
        </div>
    </div>
    <div id="loader" class="overlay display-none">
        <img class="img" src="images/loader.gif" />
    </div>
    <div>
        <div id="agGrid" style="height: 450px; width: 100%;" class="ag-theme-balham"></div>
    </div>
    <div id="uploadModal" class="modal fade">
        <%= render partial: 'upload_student_csv_list' %>        
    </div>
    <div id="addModal" class="modal fade">
        <%= render partial: 'student_new' %>        
    </div>
    <div id="editModal" class="modal fade">
        <%= render partial: 'student_edit' %>        
    </div>
</body>

<script>
    var columnDefs = [
        { headerName: "", field: "", width: 60, checkboxSelection: true, headerCheckboxSelection: true, cellStyle: { 'text-align':'center','top': '2px' } },
        { headerName: "Name", field: "name", cellStyle: { 'font-weight': 'bold', 'color': '#666666', 'padding-top': '2px', 'font-size': '15px' } },
        { headerName: "Subject", field: "subject", cellStyle: { 'font-weight': 'bold', 'color': '#666666', 'padding-top': '2px', 'font-size': '15px' } },
        { headerName: "Marks", field: "marks", cellStyle: { 'font-weight': 'bold', 'color': '#666666', 'padding-top': '2px', 'font-size': '15px' } }
    ];

    var gridOptions = {
        columnDefs: columnDefs,
        rowData: null,
        defaultColDef: {
            sortable: true,
            filter: true,
        },
        rowSelection: 'multiple',
        headerHeight: 35,
        rowHeight: 30,
        pagination: true,
        suppressExcelExport: true,
        suppressRowClickSelection: true,
        paginationPageSize: 25,
        onRowClicked: function (event) {
            const node = event.node;
            node.setSelected(!node.isSelected());
        },
    };

    function onBtnExport() {
        const columnsToInclude = ['name', 'subject', 'marks'];
        const filenameWithTimestamp = `student_data_${new Date().toISOString().replace(/:/g, '_').replace(/\..+/, '').replace('T', '_')}.csv`;
        gridOptions.api.exportDataAsCsv({
            columnKeys: columnsToInclude,
            fileName: filenameWithTimestamp
        });
    }

    function get_grid_load() {
        createNewDatasource();
    }

    $(document).ready(function () {
        get_grid_load();
        new agGrid.Grid(document.querySelector('#agGrid'), gridOptions);
    });

    function createNewDatasource(search_str = '') {
        $('#loader').removeClass('display-none');
        $.ajax({
            type: "get",
            url: "/students/get_all_student_list",
            data: { search: search_str },
            success: function (msg) {
                gridOptions.api.setRowData(msg);
            },
            error: function () {
                console.error('Error fetching data');
            },
            complete: function () {
                $('#loader').addClass('display-none');
            }
        });
    }

    function batchDelete() {
        const selected_ids = get_selected_row_ids();
        if (selected_ids.length > 0) {
            handleClickDelete(selected_ids);
        } else {
            alert('Please select at least one student');
        }
    }

    function handleClickDelete(ids) {
        Swal.fire({
            title: 'Are you sure?',
            text: 'You won\'t be able to revert this!',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                $('#loader').removeClass('display-none');
                $.ajax({
                    type: 'delete',
                    url: '/students/delete_student',
                    data: { ids: ids },
                    headers: {
                        'X-CSRF-TOKEN': '<%= form_authenticity_token %>'
                    },
                    success: function (data) {
                        Swal.fire(
                            data.message === 'Success' ? 'Deleted!' : 'Error!',
                            data.message === 'Success' ? 'Student(s) have been deleted.' : 'Student(s) not found.',
                            data.message === 'Success' ? 'success' : 'warning'
                        );
                        get_grid_load();
                    },
                    error: function () {
                        console.error('Error deleting student(s)');
                    },
                    complete: function () {
                        $('#loader').addClass('display-none');
                    }
                });
            }
        });
    }

    function get_selected_row_ids() {
        const sel_rows = [];
        gridOptions.api.forEachNodeAfterFilterAndSort(node => {
            if (node.selected && node.data) {
                sel_rows.push(node.data.id);
            }
        });
        return sel_rows;
    }

    function modalClose(id) {
        $(`#${id}`).modal('hide');
    }

    function onBtnUpload() {
        $('#upload_datafile').val('');
        $('#uploadModal').modal('show');
    }

    $('#uploadButton').click(function () {
        const fileInput = document.querySelector('#upload_datafile');
        const file = fileInput.files[0];
        if (!file) {
            alert('Please select a CSV file.');
            return;
        }
        const formData = new FormData();
        formData.append('csv_file', file);
        $.ajax({
            type: 'POST',
            url: '/students/save_mass_data_upload',
            data: formData,
            processData: false,
            contentType: false,
            headers: {
                'X-CSRF-TOKEN': '<%= form_authenticity_token %>'
            },
            success: function (response) {
                alert(response);
                $('#uploadModal').modal('hide');
                get_grid_load();
            },
            error: function (xhr) {
                console.error(xhr.responseText);
            }
        });
    });

    function onBtnAdd() {
        $('#addModal').modal('show');
    }

    function onBtnEdit() {
        const selected_id = get_selected_row_ids();
        if (selected_id.length === 1) {
            handleClickEdit(selected_id[0]);
        } else {
            alert('Please select one student');
        }
    }

    function handleClickEdit(id) {
        $.ajax({
            type: 'get',
            url: '/students/get_student_data',
            data: { id: id },
            success: function (data) {
                $('#editForm').attr('action', `/students/${data.id}`).attr('method', 'patch');
                $('#name').val(data.name.toUpperCase()).attr('name', 'student[name]');
                $('#subject').val(data.subject.toUpperCase()).attr('name', 'student[subject]');
                $('#marks').val(data.marks).attr('name', 'student[marks]');
                $('#editModal').modal('show');
            },
            error: function (xhr) {
                console.error(xhr.responseText);
            }
        });
    }

    function handleSearchChange(value) {
        createNewDatasource(value || '');
    }

    function handleFormSubmit(formElement, method, modal_id) {
        const formData = new FormData(formElement);
        const csrfToken = $('meta[name="csrf-token"]').attr('content');

        fetch(formElement.action, {
            method: method,
            headers: {
                'X-CSRF-Token': csrfToken,
                'Accept': 'application/json',
            },
            body: formData,
        })
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            return response.json();
        })
        .then(data => {
            alert(data.success ? data.message : 'Action failed.');
            if (data.success) {
                $(`#${modal_id}`).modal('hide');
                get_grid_load();
            }
        })
        .catch(error => {
            get_grid_load();
            console.error('Error:', error);
            alert('An error occurred.');
        });
    }

</script>